#GLPI MySQL Container
glpi-db:
 image: mariadb
 container_name: glpi-db
 volumes:
  - ./mysql:/var/lib/mysql
 environment:
  - SET_CONTAINER_TIMEZONE=true
  - CONTAINER_TIMEZONE=America/Sao_Paulo
 env_file:
  - ./mysql.env
 restart: always

# GLPI APP Container
glpi-app:
 image: glpi
 container_name : glpi-app
 volumes:
  - ./public_html:/var/www/html
 links:
  - glpi-db:glpi.db
 ports:
  - "80:80"
  - "443:443"
 environment:
  - SET_CONTAINER_TIMEZONE=true
  - CONTAINER_TIMEZONE=America/Sao_Paulo
 tty: true
 restart: always
